package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	
)

type AchievementData struct {
	AchievementDesc     map[string]json.Number   `json:"AchievementDesc"`
	AchievementDescPS   map[string]json.Number   `json:"AchievementDescPS"`
	AchievementID       json.Number              `json:"AchievementID"`
	AchievementTitle    map[string]json.Number   `json:"AchievementTitle"`
	HideAchievementDesc map[string]json.Number   `json:"HideAchievementDesc"`
	LinearQuestID       json.Number              `json:"LinearQuestID"`
	PSTrophyID          string                   `json:"PSTrophyID"`
	ParamList           []map[string]json.Number `json:"ParamList"`
	Priority            json.Number              `json:"Priority"`
	QuestID             json.Number              `json:"QuestID"`
	Rarity              string                   `json:"Rarity"`
	RecordText          map[string]json.Number   `json:"RecordText"`
	RecordType          string                   `json:"RecordType"`
	SeriesID            json.Number              `json:"SeriesID"`
	ShowType            string                   `json:"ShowType"`
}
type AchievementDataAccessor struct {
	_data []AchievementData
}

// LoadData retrieves the data. Must be called before AchievementData.GroupData
func (a *AchievementDataAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/AchievementData.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *AchievementDataAccessor) Raw() ([]AchievementData, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []AchievementData{}, err
		}
	}
	return a._data, nil
}
