package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type ActivityAvatarPromotion struct {
	AttackAdd         map[string]json.Number   `json:"AttackAdd"`
	AttackBase        map[string]json.Number   `json:"AttackBase"`
	AvatarID          json.Number              `json:"AvatarID"`
	BaseAggro         map[string]json.Number   `json:"BaseAggro"`
	CriticalChance    map[string]json.Number   `json:"CriticalChance"`
	CriticalDamage    map[string]json.Number   `json:"CriticalDamage"`
	DefenceAdd        map[string]json.Number   `json:"DefenceAdd"`
	DefenceBase       map[string]json.Number   `json:"DefenceBase"`
	HPAdd             map[string]json.Number   `json:"HPAdd"`
	HPBase            map[string]json.Number   `json:"HPBase"`
	MaxLevel          json.Number              `json:"MaxLevel"`
	Promotion         json.Number              `json:"Promotion"`
	PromotionCostList []map[string]json.Number `json:"PromotionCostList"`
	SpeedBase         map[string]json.Number   `json:"SpeedBase"`
}
type ActivityAvatarPromotionAccessor struct {
	_data []ActivityAvatarPromotion
}

// LoadData retrieves the data. Must be called before ActivityAvatarPromotion.GroupData
func (a *ActivityAvatarPromotionAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ActivityAvatarPromotion.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ActivityAvatarPromotionAccessor) Raw() ([]ActivityAvatarPromotion, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ActivityAvatarPromotion{}, err
		}
	}
	return a._data, nil
}
