package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type ActivityModuleFindTrotter struct {
	ActivityID         float64   `json:"ActivityID"`
	ActivityModuleID   float64   `json:"ActivityModuleID"`
	Aim01              hash.Hash `json:"Aim01"`
	Aim02              hash.Hash `json:"Aim02"`
	FinishSubMissionID float64   `json:"FinishSubMissionID"`
	MissionID          float64   `json:"MissionID"`
	Order              float64   `json:"Order"`
	Result01           hash.Hash `json:"Result01"`
	Result02           hash.Hash `json:"Result02"`
	RewardQuestID      float64   `json:"RewardQuestID"`
	StartSubMissionID  float64   `json:"StartSubMissionID"`
	Title              hash.Hash `json:"Title"`
}
type ActivityModuleFindTrotterAccessor struct {
	_data                   []ActivityModuleFindTrotter
	_dataActivityModuleID   map[float64]ActivityModuleFindTrotter
	_dataFinishSubMissionID map[float64]ActivityModuleFindTrotter
	_dataMissionID          map[float64]ActivityModuleFindTrotter
	_dataOrder              map[float64]ActivityModuleFindTrotter
	_dataRewardQuestID      map[float64]ActivityModuleFindTrotter
	_dataStartSubMissionID  map[float64]ActivityModuleFindTrotter
}

// LoadData retrieves the data. Must be called before ActivityModuleFindTrotter.GroupData
func (a *ActivityModuleFindTrotterAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ActivityModuleFindTrotter.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ActivityModuleFindTrotterAccessor) Raw() ([]ActivityModuleFindTrotter, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ActivityModuleFindTrotter{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ActivityModuleFindTrotterAccessor.LoadData to preload everything
func (a *ActivityModuleFindTrotterAccessor) GroupData() {
	for _, d := range a._data {
		a._dataActivityModuleID[d.ActivityModuleID] = d
		a._dataFinishSubMissionID[d.FinishSubMissionID] = d
		a._dataMissionID[d.MissionID] = d
		a._dataOrder[d.Order] = d
		a._dataRewardQuestID[d.RewardQuestID] = d
		a._dataStartSubMissionID[d.StartSubMissionID] = d
	}
}

// ByActivityModuleID returns the ActivityModuleFindTrotter uniquely identified by ActivityModuleID
//
// Error is only non-nil if the source errors out
func (a *ActivityModuleFindTrotterAccessor) ByActivityModuleID(identifier float64) (ActivityModuleFindTrotter, error) {
	if a._dataActivityModuleID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ActivityModuleFindTrotter{}, err
			}
		}
		a.GroupData()
	}
	return a._dataActivityModuleID[identifier], nil
}

// ByFinishSubMissionID returns the ActivityModuleFindTrotter uniquely identified by FinishSubMissionID
//
// Error is only non-nil if the source errors out
func (a *ActivityModuleFindTrotterAccessor) ByFinishSubMissionID(identifier float64) (ActivityModuleFindTrotter, error) {
	if a._dataFinishSubMissionID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ActivityModuleFindTrotter{}, err
			}
		}
		a.GroupData()
	}
	return a._dataFinishSubMissionID[identifier], nil
}

// ByMissionID returns the ActivityModuleFindTrotter uniquely identified by MissionID
//
// Error is only non-nil if the source errors out
func (a *ActivityModuleFindTrotterAccessor) ByMissionID(identifier float64) (ActivityModuleFindTrotter, error) {
	if a._dataMissionID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ActivityModuleFindTrotter{}, err
			}
		}
		a.GroupData()
	}
	return a._dataMissionID[identifier], nil
}

// ByOrder returns the ActivityModuleFindTrotter uniquely identified by Order
//
// Error is only non-nil if the source errors out
func (a *ActivityModuleFindTrotterAccessor) ByOrder(identifier float64) (ActivityModuleFindTrotter, error) {
	if a._dataOrder == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ActivityModuleFindTrotter{}, err
			}
		}
		a.GroupData()
	}
	return a._dataOrder[identifier], nil
}

// ByRewardQuestID returns the ActivityModuleFindTrotter uniquely identified by RewardQuestID
//
// Error is only non-nil if the source errors out
func (a *ActivityModuleFindTrotterAccessor) ByRewardQuestID(identifier float64) (ActivityModuleFindTrotter, error) {
	if a._dataRewardQuestID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ActivityModuleFindTrotter{}, err
			}
		}
		a.GroupData()
	}
	return a._dataRewardQuestID[identifier], nil
}

// ByStartSubMissionID returns the ActivityModuleFindTrotter uniquely identified by StartSubMissionID
//
// Error is only non-nil if the source errors out
func (a *ActivityModuleFindTrotterAccessor) ByStartSubMissionID(identifier float64) (ActivityModuleFindTrotter, error) {
	if a._dataStartSubMissionID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ActivityModuleFindTrotter{}, err
			}
		}
		a.GroupData()
	}
	return a._dataStartSubMissionID[identifier], nil
}
