package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"net/http"
	"io"
	"encoding/json"
)

type ActivityExpeditionGroup struct {
	ActivityModuleID float64   `json:"ActivityModuleID"`
	ExpeditionIdList []float64 `json:"ExpeditionIdList"`
	GroupID          float64   `json:"GroupID"`
}
type ActivityExpeditionGroupAccessor struct {
	_data                 []ActivityExpeditionGroup
	_dataGroupID          map[float64]ActivityExpeditionGroup
	_dataActivityModuleID map[float64]ActivityExpeditionGroup
}

// LoadData retrieves the data. Must be called before ActivityExpeditionGroup.GroupData
func (a *ActivityExpeditionGroupAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ActivityExpeditionGroup.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ActivityExpeditionGroupAccessor) Raw() ([]ActivityExpeditionGroup, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ActivityExpeditionGroup{}, err
		}
		a.GroupData()
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ActivityExpeditionGroupAccessor.LoadData to preload everything
func (a *ActivityExpeditionGroupAccessor) GroupData() {
	for _, d := range a._data {
		a._dataGroupID[d.GroupID] = d
		a._dataActivityModuleID[d.ActivityModuleID] = d
	}
}

// ByGroupID returns the ActivityExpeditionGroup uniquely identified by GroupID
//
// Error is only non-nil if the source errors out
func (a *ActivityExpeditionGroupAccessor) ByGroupID(identifier float64) (ActivityExpeditionGroup, error) {
	if a._dataGroupID == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityExpeditionGroup{}, err
		}
		a.GroupData()
	}
	return a._dataGroupID[identifier], nil
}

// ByActivityModuleID returns the ActivityExpeditionGroup uniquely identified by ActivityModuleID
//
// Error is only non-nil if the source errors out
func (a *ActivityExpeditionGroupAccessor) ByActivityModuleID(identifier float64) (ActivityExpeditionGroup, error) {
	if a._dataActivityModuleID == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityExpeditionGroup{}, err
		}
		a.GroupData()
	}
	return a._dataActivityModuleID[identifier], nil
}
