package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type ActivityRaidCollectionTab struct {
	RaidCollectionGroupList []json.Number          `json:"RaidCollectionGroupList"`
	RaidCollectionTabID     json.Number            `json:"RaidCollectionTabID"`
	RaidCollectionTabName   map[string]json.Number `json:"RaidCollectionTabName"`
	RaidCollectionType      string                 `json:"RaidCollectionType"`
}
type ActivityRaidCollectionTabAccessor struct {
	_data []ActivityRaidCollectionTab
}

// LoadData retrieves the data. Must be called before ActivityRaidCollectionTab.GroupData
func (a *ActivityRaidCollectionTabAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ActivityRaidCollectionTab.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ActivityRaidCollectionTabAccessor) Raw() ([]ActivityRaidCollectionTab, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ActivityRaidCollectionTab{}, err
		}
	}
	return a._data, nil
}
