package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type ActivityAvatarSkillConfig struct {
	AttackType              string          `json:"AttackType"`
	BPAdd                   hash.IntValue   `json:"BPAdd"`
	BPNeed                  hash.IntValue   `json:"BPNeed"`
	CoolDown                float64         `json:"CoolDown"`
	DelayRatio              hash.IntValue   `json:"DelayRatio"`
	ExtraEffectIDList       []interface{}   `json:"ExtraEffectIDList"`
	InitCoolDown            float64         `json:"InitCoolDown"`
	Level                   float64         `json:"Level"`
	LevelUpCostList         []interface{}   `json:"LevelUpCostList"`
	MaxLevel                float64         `json:"MaxLevel"`
	ParamList               []hash.IntValue `json:"ParamList"`
	RatedRankID             []interface{}   `json:"RatedRankID"`
	RatedSkillTreeID        []interface{}   `json:"RatedSkillTreeID"`
	SPBase                  hash.IntValue   `json:"SPBase"`
	SPMultipleRatio         hash.IntValue   `json:"SPMultipleRatio"`
	SPNeed                  hash.IntValue   `json:"SPNeed"`
	ShowDamageList          []interface{}   `json:"ShowDamageList"`
	ShowHealList            []interface{}   `json:"ShowHealList"`
	ShowStanceList          []hash.IntValue `json:"ShowStanceList"`
	SimpleExtraEffectIDList []interface{}   `json:"SimpleExtraEffectIDList"`
	SimpleParamList         []hash.IntValue `json:"SimpleParamList"`
	SimpleSkillDesc         hash.Hash       `json:"SimpleSkillDesc"`
	SkillComboValueDelta    hash.IntValue   `json:"SkillComboValueDelta"`
	SkillDesc               hash.Hash       `json:"SkillDesc"`
	SkillEffect             string          `json:"SkillEffect"`
	SkillID                 float64         `json:"SkillID"`
	SkillIcon               string          `json:"SkillIcon"`
	SkillName               hash.Hash       `json:"SkillName"`
	SkillTag                hash.Hash       `json:"SkillTag"`
	SkillTriggerKey         string          `json:"SkillTriggerKey"`
	SkillTypeDesc           hash.Hash       `json:"SkillTypeDesc"`
	StanceDamageDisplay     float64         `json:"StanceDamageDisplay"`
	StanceDamageType        string          `json:"StanceDamageType"`
	UltraSkillIcon          string          `json:"UltraSkillIcon"`
}
type ActivityAvatarSkillConfigAccessor struct {
	_data        []ActivityAvatarSkillConfig
	_dataSkillID map[float64]ActivityAvatarSkillConfig
}

// LoadData retrieves the data. Must be called before ActivityAvatarSkillConfig.GroupData
func (a *ActivityAvatarSkillConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ActivityAvatarSkillConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ActivityAvatarSkillConfigAccessor) Raw() ([]ActivityAvatarSkillConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ActivityAvatarSkillConfig{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ActivityAvatarSkillConfigAccessor.LoadData to preload everything
func (a *ActivityAvatarSkillConfigAccessor) GroupData() {
	a._dataSkillID = map[float64]ActivityAvatarSkillConfig{}
	for _, d := range a._data {
		a._dataSkillID[d.SkillID] = d
	}
}

// BySkillID returns the ActivityAvatarSkillConfig uniquely identified by SkillID
//
// Error is only non-nil if the source errors out
func (a *ActivityAvatarSkillConfigAccessor) BySkillID(identifier float64) (ActivityAvatarSkillConfig, error) {
	if a._dataSkillID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ActivityAvatarSkillConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataSkillID[identifier], nil
}
