package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type ActivityTelevisionStage struct {
	ActivityModuleID         float64   `json:"ActivityModuleID"`
	ChannelName              hash.Hash `json:"ChannelName"`
	Desc                     hash.Hash `json:"Desc"`
	EntranceID               float64   `json:"EntranceID"`
	GotoID                   float64   `json:"GotoID"`
	ImagePath                string    `json:"ImagePath"`
	MappingInfo              float64   `json:"MappingInfo"`
	MiniImagePath            string    `json:"MiniImagePath"`
	MissionID                float64   `json:"MissionID"`
	OriginalDesc             hash.Hash `json:"OriginalDesc"`
	OriginalImagePath        string    `json:"OriginalImagePath"`
	OriginalMiniImagePath    string    `json:"OriginalMiniImagePath"`
	OriginalOutlineImagePath string    `json:"OriginalOutlineImagePath"`
	OriginalStageName        hash.Hash `json:"OriginalStageName"`
	QuestGroupID             float64   `json:"QuestGroupID"`
	Season                   float64   `json:"Season"`
	StageName                hash.Hash `json:"StageName"`
	TelevisionID             float64   `json:"TelevisionID"`
}
type ActivityTelevisionStageAccessor struct {
	_data                      []ActivityTelevisionStage
	_dataTelevisionID          map[float64]ActivityTelevisionStage
	_dataActivityModuleID      map[float64]ActivityTelevisionStage
	_dataEntranceID            map[float64]ActivityTelevisionStage
	_dataImagePath             map[string]ActivityTelevisionStage
	_dataOriginalMiniImagePath map[string]ActivityTelevisionStage
	_dataGotoID                map[float64]ActivityTelevisionStage
	_dataQuestGroupID          map[float64]ActivityTelevisionStage
	_dataMissionID             map[float64]ActivityTelevisionStage
	_dataOriginalImagePath     map[string]ActivityTelevisionStage
	_dataMiniImagePath         map[string]ActivityTelevisionStage
	_dataMappingInfo           map[float64]ActivityTelevisionStage
}

// LoadData retrieves the data. Must be called before ActivityTelevisionStage.GroupData
func (a *ActivityTelevisionStageAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ActivityTelevisionStage.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ActivityTelevisionStageAccessor) Raw() ([]ActivityTelevisionStage, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ActivityTelevisionStageAccessor.LoadData to preload everything
func (a *ActivityTelevisionStageAccessor) GroupData() {
	for _, d := range a._data {
		a._dataTelevisionID[d.TelevisionID] = d
		a._dataActivityModuleID[d.ActivityModuleID] = d
		a._dataEntranceID[d.EntranceID] = d
		a._dataImagePath[d.ImagePath] = d
		a._dataOriginalMiniImagePath[d.OriginalMiniImagePath] = d
		a._dataGotoID[d.GotoID] = d
		a._dataQuestGroupID[d.QuestGroupID] = d
		a._dataMissionID[d.MissionID] = d
		a._dataOriginalImagePath[d.OriginalImagePath] = d
		a._dataMiniImagePath[d.MiniImagePath] = d
		a._dataMappingInfo[d.MappingInfo] = d
	}
}

// ByTelevisionID returns the ActivityTelevisionStage uniquely identified by TelevisionID
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByTelevisionID(identifier float64) (ActivityTelevisionStage, error) {
	if a._dataTelevisionID == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataTelevisionID[identifier], nil
}

// ByActivityModuleID returns the ActivityTelevisionStage uniquely identified by ActivityModuleID
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByActivityModuleID(identifier float64) (ActivityTelevisionStage, error) {
	if a._dataActivityModuleID == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataActivityModuleID[identifier], nil
}

// ByEntranceID returns the ActivityTelevisionStage uniquely identified by EntranceID
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByEntranceID(identifier float64) (ActivityTelevisionStage, error) {
	if a._dataEntranceID == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataEntranceID[identifier], nil
}

// ByImagePath returns the ActivityTelevisionStage uniquely identified by ImagePath
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByImagePath(identifier string) (ActivityTelevisionStage, error) {
	if a._dataImagePath == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataImagePath[identifier], nil
}

// ByOriginalMiniImagePath returns the ActivityTelevisionStage uniquely identified by OriginalMiniImagePath
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByOriginalMiniImagePath(identifier string) (ActivityTelevisionStage, error) {
	if a._dataOriginalMiniImagePath == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataOriginalMiniImagePath[identifier], nil
}

// ByGotoID returns the ActivityTelevisionStage uniquely identified by GotoID
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByGotoID(identifier float64) (ActivityTelevisionStage, error) {
	if a._dataGotoID == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataGotoID[identifier], nil
}

// ByQuestGroupID returns the ActivityTelevisionStage uniquely identified by QuestGroupID
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByQuestGroupID(identifier float64) (ActivityTelevisionStage, error) {
	if a._dataQuestGroupID == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataQuestGroupID[identifier], nil
}

// ByMissionID returns the ActivityTelevisionStage uniquely identified by MissionID
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByMissionID(identifier float64) (ActivityTelevisionStage, error) {
	if a._dataMissionID == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataMissionID[identifier], nil
}

// ByOriginalImagePath returns the ActivityTelevisionStage uniquely identified by OriginalImagePath
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByOriginalImagePath(identifier string) (ActivityTelevisionStage, error) {
	if a._dataOriginalImagePath == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataOriginalImagePath[identifier], nil
}

// ByMiniImagePath returns the ActivityTelevisionStage uniquely identified by MiniImagePath
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByMiniImagePath(identifier string) (ActivityTelevisionStage, error) {
	if a._dataMiniImagePath == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataMiniImagePath[identifier], nil
}

// ByMappingInfo returns the ActivityTelevisionStage uniquely identified by MappingInfo
//
// Error is only non-nil if the source errors out
func (a *ActivityTelevisionStageAccessor) ByMappingInfo(identifier float64) (ActivityTelevisionStage, error) {
	if a._dataMappingInfo == nil {
		err := a.LoadData()
		if err != nil {
			return ActivityTelevisionStage{}, err
		}
		a.GroupData()
	}
	return a._dataMappingInfo[identifier], nil
}
