package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type AdventurePlayer struct {
	AvatarID                  json.Number            `json:"AvatarID"`
	DefaultAvatarHeadIconPath string                 `json:"DefaultAvatarHeadIconPath"`
	ID                        json.Number            `json:"ID"`
	MazeSkillIdList           []json.Number          `json:"MazeSkillIdList"`
	PlayerJsonPath            string                 `json:"PlayerJsonPath"`
	PlayerName                map[string]json.Number `json:"PlayerName"`
	PlayerPrefabPath          string                 `json:"PlayerPrefabPath"`
}
type AdventurePlayerAccessor struct {
	_data                          []AdventurePlayer
	_dataDefaultAvatarHeadIconPath map[string]AdventurePlayer
	_dataPlayerJsonPath            map[string]AdventurePlayer
	_dataPlayerPrefabPath          map[string]AdventurePlayer
}

// LoadData retrieves the data. Must be called before AdventurePlayer.GroupData
func (a *AdventurePlayerAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/AdventurePlayer.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *AdventurePlayerAccessor) Raw() ([]AdventurePlayer, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []AdventurePlayer{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with AdventurePlayerAccessor.LoadData to preload everything
func (a *AdventurePlayerAccessor) GroupData() {
	a._dataDefaultAvatarHeadIconPath = map[string]AdventurePlayer{}
	a._dataPlayerJsonPath = map[string]AdventurePlayer{}
	a._dataPlayerPrefabPath = map[string]AdventurePlayer{}
	for _, d := range a._data {
		a._dataDefaultAvatarHeadIconPath[d.DefaultAvatarHeadIconPath] = d
		a._dataPlayerJsonPath[d.PlayerJsonPath] = d
		a._dataPlayerPrefabPath[d.PlayerPrefabPath] = d
	}
}

// ByDefaultAvatarHeadIconPath returns the AdventurePlayer uniquely identified by DefaultAvatarHeadIconPath
//
// Error is only non-nil if the source errors out
func (a *AdventurePlayerAccessor) ByDefaultAvatarHeadIconPath(identifier string) (AdventurePlayer, error) {
	if a._dataDefaultAvatarHeadIconPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return AdventurePlayer{}, err
			}
		}
		a.GroupData()
	}
	return a._dataDefaultAvatarHeadIconPath[identifier], nil
}

// ByPlayerJsonPath returns the AdventurePlayer uniquely identified by PlayerJsonPath
//
// Error is only non-nil if the source errors out
func (a *AdventurePlayerAccessor) ByPlayerJsonPath(identifier string) (AdventurePlayer, error) {
	if a._dataPlayerJsonPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return AdventurePlayer{}, err
			}
		}
		a.GroupData()
	}
	return a._dataPlayerJsonPath[identifier], nil
}

// ByPlayerPrefabPath returns the AdventurePlayer uniquely identified by PlayerPrefabPath
//
// Error is only non-nil if the source errors out
func (a *AdventurePlayerAccessor) ByPlayerPrefabPath(identifier string) (AdventurePlayer, error) {
	if a._dataPlayerPrefabPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return AdventurePlayer{}, err
			}
		}
		a.GroupData()
	}
	return a._dataPlayerPrefabPath[identifier], nil
}
