package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type AetherDivideTrainerLevel struct {
	ID               json.Number            `json:"ID"`
	IconPath         string                 `json:"IconPath"`
	Name             map[string]json.Number `json:"Name"`
	QuestID          json.Number            `json:"QuestID"`
	QuestList        []json.Number          `json:"QuestList"`
	RareMonsterNumID json.Number            `json:"RareMonsterNumID"`
}
type AetherDivideTrainerLevelAccessor struct {
	_data         []AetherDivideTrainerLevel
	_dataIconPath map[string]AetherDivideTrainerLevel
}

// LoadData retrieves the data. Must be called before AetherDivideTrainerLevel.GroupData
func (a *AetherDivideTrainerLevelAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/AetherDivideTrainerLevel.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *AetherDivideTrainerLevelAccessor) Raw() ([]AetherDivideTrainerLevel, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []AetherDivideTrainerLevel{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with AetherDivideTrainerLevelAccessor.LoadData to preload everything
func (a *AetherDivideTrainerLevelAccessor) GroupData() {
	a._dataIconPath = map[string]AetherDivideTrainerLevel{}
	for _, d := range a._data {
		a._dataIconPath[d.IconPath] = d
	}
}

// ByIconPath returns the AetherDivideTrainerLevel uniquely identified by IconPath
//
// Error is only non-nil if the source errors out
func (a *AetherDivideTrainerLevelAccessor) ByIconPath(identifier string) (AetherDivideTrainerLevel, error) {
	if a._dataIconPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return AetherDivideTrainerLevel{}, err
			}
		}
		a.GroupData()
	}
	return a._dataIconPath[identifier], nil
}
