package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type AlleyActivityQuest struct {
	ID           json.Number            `json:"ID"`
	MainTabTitle map[string]json.Number `json:"MainTabTitle"`
	QuestList    []json.Number          `json:"QuestList"`
	SubTab       json.Number            `json:"SubTab"`
}
type AlleyActivityQuestAccessor struct {
	_data []AlleyActivityQuest
}

// LoadData retrieves the data. Must be called before AlleyActivityQuest.GroupData
func (a *AlleyActivityQuestAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/AlleyActivityQuest.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *AlleyActivityQuestAccessor) Raw() ([]AlleyActivityQuest, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []AlleyActivityQuest{}, err
		}
	}
	return a._data, nil
}
