package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"net/http"
	"io"
	"encoding/json"
)

type AreaMapMenuIcon struct {
	ID       float64 `json:"ID"`
	IconPath string  `json:"IconPath"`
}
type AreaMapMenuIconAccessor struct {
	_data         []AreaMapMenuIcon
	_dataID       map[float64]AreaMapMenuIcon
	_dataIconPath map[string]AreaMapMenuIcon
}

// LoadData retrieves the data. Must be called before AreaMapMenuIcon.GroupData
func (a *AreaMapMenuIconAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/AreaMapMenuIcon.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *AreaMapMenuIconAccessor) Raw() ([]AreaMapMenuIcon, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []AreaMapMenuIcon{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with AreaMapMenuIconAccessor.LoadData to preload everything
func (a *AreaMapMenuIconAccessor) GroupData() {
	a._dataID = map[float64]AreaMapMenuIcon{}
	a._dataIconPath = map[string]AreaMapMenuIcon{}
	for _, d := range a._data {
		a._dataID[d.ID] = d
		a._dataIconPath[d.IconPath] = d
	}
}

// ByID returns the AreaMapMenuIcon uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *AreaMapMenuIconAccessor) ByID(identifier float64) (AreaMapMenuIcon, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return AreaMapMenuIcon{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}

// ByIconPath returns the AreaMapMenuIcon uniquely identified by IconPath
//
// Error is only non-nil if the source errors out
func (a *AreaMapMenuIconAccessor) ByIconPath(identifier string) (AreaMapMenuIcon, error) {
	if a._dataIconPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return AreaMapMenuIcon{}, err
			}
		}
		a.GroupData()
	}
	return a._dataIconPath[identifier], nil
}
