package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type AtlasUnlockTextmap struct {
	UnlockDesc hash.Hash `json:"UnlockDesc"`
	UnlockID   float64   `json:"UnlockID"`
}
type AtlasUnlockTextmapAccessor struct {
	_data         []AtlasUnlockTextmap
	_dataUnlockID map[float64]AtlasUnlockTextmap
}

// LoadData retrieves the data. Must be called before AtlasUnlockTextmap.GroupData
func (a *AtlasUnlockTextmapAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/AtlasUnlockTextmap.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *AtlasUnlockTextmapAccessor) Raw() ([]AtlasUnlockTextmap, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []AtlasUnlockTextmap{}, err
		}
		a.GroupData()
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with AtlasUnlockTextmapAccessor.LoadData to preload everything
func (a *AtlasUnlockTextmapAccessor) GroupData() {
	for _, d := range a._data {
		a._dataUnlockID[d.UnlockID] = d
	}
}

// ByUnlockID returns the AtlasUnlockTextmap uniquely identified by UnlockID
//
// Error is only non-nil if the source errors out
func (a *AtlasUnlockTextmapAccessor) ByUnlockID(identifier float64) (AtlasUnlockTextmap, error) {
	if a._dataUnlockID == nil {
		err := a.LoadData()
		if err != nil {
			return AtlasUnlockTextmap{}, err
		}
		a.GroupData()
	}
	return a._dataUnlockID[identifier], nil
}
