package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type AvatarDetailTabConfig struct {
	ID       json.Number `json:"ID"`
	IconPath string      `json:"IconPath"`
	TabName  string      `json:"TabName"`
}
type AvatarDetailTabConfigAccessor struct {
	_data         []AvatarDetailTabConfig
	_dataID       map[json.Number]AvatarDetailTabConfig
	_dataIconPath map[string]AvatarDetailTabConfig
	_dataTabName  map[string]AvatarDetailTabConfig
}

// LoadData retrieves the data. Must be called before AvatarDetailTabConfig.GroupData
func (a *AvatarDetailTabConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/AvatarDetailTabConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *AvatarDetailTabConfigAccessor) Raw() ([]AvatarDetailTabConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []AvatarDetailTabConfig{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with AvatarDetailTabConfigAccessor.LoadData to preload everything
func (a *AvatarDetailTabConfigAccessor) GroupData() {
	a._dataID = map[json.Number]AvatarDetailTabConfig{}
	a._dataIconPath = map[string]AvatarDetailTabConfig{}
	a._dataTabName = map[string]AvatarDetailTabConfig{}
	for _, d := range a._data {
		a._dataID[d.ID] = d
		a._dataIconPath[d.IconPath] = d
		a._dataTabName[d.TabName] = d
	}
}

// ByID returns the AvatarDetailTabConfig uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *AvatarDetailTabConfigAccessor) ByID(identifier json.Number) (AvatarDetailTabConfig, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return AvatarDetailTabConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}

// ByIconPath returns the AvatarDetailTabConfig uniquely identified by IconPath
//
// Error is only non-nil if the source errors out
func (a *AvatarDetailTabConfigAccessor) ByIconPath(identifier string) (AvatarDetailTabConfig, error) {
	if a._dataIconPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return AvatarDetailTabConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataIconPath[identifier], nil
}

// ByTabName returns the AvatarDetailTabConfig uniquely identified by TabName
//
// Error is only non-nil if the source errors out
func (a *AvatarDetailTabConfigAccessor) ByTabName(identifier string) (AvatarDetailTabConfig, error) {
	if a._dataTabName == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return AvatarDetailTabConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataTabName[identifier], nil
}
