package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type ChallengeMazeGroupExtra struct {
	GroupID              json.Number `json:"GroupID"`
	ThemePosterBgPicPath string      `json:"ThemePosterBgPicPath"`
}
type ChallengeMazeGroupExtraAccessor struct {
	_data []ChallengeMazeGroupExtra
}

// LoadData retrieves the data. Must be called before ChallengeMazeGroupExtra.GroupData
func (a *ChallengeMazeGroupExtraAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ChallengeMazeGroupExtra.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ChallengeMazeGroupExtraAccessor) Raw() ([]ChallengeMazeGroupExtra, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ChallengeMazeGroupExtra{}, err
		}
	}
	return a._data, nil
}
