package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"net/http"
	"io"
	"encoding/json"
)

type ChallengeBossMazeExtra struct {
	ID         float64 `json:"ID"`
	MonsterID1 float64 `json:"MonsterID1"`
	MonsterID2 float64 `json:"MonsterID2"`
}
type ChallengeBossMazeExtraAccessor struct {
	_data   []ChallengeBossMazeExtra
	_dataID map[float64]ChallengeBossMazeExtra
}

// LoadData retrieves the data. Must be called before ChallengeBossMazeExtra.GroupData
func (a *ChallengeBossMazeExtraAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ChallengeBossMazeExtra.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ChallengeBossMazeExtraAccessor) Raw() ([]ChallengeBossMazeExtra, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ChallengeBossMazeExtra{}, err
		}
		a.GroupData()
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ChallengeBossMazeExtraAccessor.LoadData to preload everything
func (a *ChallengeBossMazeExtraAccessor) GroupData() {
	for _, d := range a._data {
		a._dataID[d.ID] = d
	}
}

// ByID returns the ChallengeBossMazeExtra uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *ChallengeBossMazeExtraAccessor) ByID(identifier float64) (ChallengeBossMazeExtra, error) {
	if a._dataID == nil {
		err := a.LoadData()
		if err != nil {
			return ChallengeBossMazeExtra{}, err
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}
