package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type ClockParkChapterConfig struct {
	ChapterAutoUnlock              json.Number            `json:"ChapterAutoUnlock"`
	ChapterGamePlayRoundRandomList []json.Number          `json:"ChapterGamePlayRoundRandomList"`
	ChapterID                      json.Number            `json:"ChapterID"`
	ChapterRoundIDList             []json.Number          `json:"ChapterRoundIDList"`
	ChapterStoryIDList             []json.Number          `json:"ChapterStoryIDList"`
	ChapterTitle                   map[string]json.Number `json:"ChapterTitle"`
	ChapterType                    string                 `json:"ChapterType"`
	CheckPointList                 []json.Number          `json:"CheckPointList"`
	NextChapterID                  []json.Number          `json:"NextChapterID"`
	RewardID                       json.Number            `json:"RewardID"`
	RewardProgress                 json.Number            `json:"RewardProgress"`
	SuccessToRoundID               json.Number            `json:"SuccessToRoundID"`
}
type ClockParkChapterConfigAccessor struct {
	_data []ClockParkChapterConfig
}

// LoadData retrieves the data. Must be called before ClockParkChapterConfig.GroupData
func (a *ClockParkChapterConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ClockParkChapterConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ClockParkChapterConfigAccessor) Raw() ([]ClockParkChapterConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ClockParkChapterConfig{}, err
		}
	}
	return a._data, nil
}
