package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type ClockParkRound struct {
	DiceSpecialDisplay bool        `json:"DiceSpecialDisplay"`
	RoundID            json.Number `json:"RoundID"`
	RoundType          string      `json:"RoundType"`
}
type ClockParkRoundAccessor struct {
	_data []ClockParkRound
}

// LoadData retrieves the data. Must be called before ClockParkRound.GroupData
func (a *ClockParkRoundAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ClockParkRound.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ClockParkRoundAccessor) Raw() ([]ClockParkRound, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ClockParkRound{}, err
		}
	}
	return a._data, nil
}
