package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type ConstValueClient struct {
	ConstValueName string                `json:"ConstValueName"`
	Value          ConstValueClientValue `json:"Value"`
}
type ConstValueClientValue struct {
	ArrayValue  []hash.IntValue          `json:"ArrayValue"`
	BoolValue   bool                     `json:"BoolValue"`
	FloatValue  float64                  `json:"FloatValue"`
	IntValue    float64                  `json:"IntValue"`
	MapValue    map[string]hash.IntValue `json:"MapValue"`
	StringValue string                   `json:"StringValue"`
}
type ConstValueClientAccessor struct {
	_data               []ConstValueClient
	_dataConstValueName map[string]ConstValueClient
}

// LoadData retrieves the data. Must be called before ConstValueClient.GroupData
func (a *ConstValueClientAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ConstValueClient.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ConstValueClientAccessor) Raw() ([]ConstValueClient, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ConstValueClient{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ConstValueClientAccessor.LoadData to preload everything
func (a *ConstValueClientAccessor) GroupData() {
	a._dataConstValueName = map[string]ConstValueClient{}
	for _, d := range a._data {
		a._dataConstValueName[d.ConstValueName] = d
	}
}

// ByConstValueName returns the ConstValueClient uniquely identified by ConstValueName
//
// Error is only non-nil if the source errors out
func (a *ConstValueClientAccessor) ByConstValueName(identifier string) (ConstValueClient, error) {
	if a._dataConstValueName == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ConstValueClient{}, err
			}
		}
		a.GroupData()
	}
	return a._dataConstValueName[identifier], nil
}
