package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"net/http"
	"io"
	"encoding/json"
)

type DailyMissionData struct {
	DailyMissionType  float64 `json:"DailyMissionType"`
	GroupID           float64 `json:"GroupID"`
	ID                float64 `json:"ID"`
	IconPath          string  `json:"IconPath"`
	QuestID           float64 `json:"QuestID"`
	UnlockMainMission float64 `json:"UnlockMainMission"`
}
type DailyMissionDataAccessor struct {
	_data   []DailyMissionData
	_dataID map[float64]DailyMissionData
}

// LoadData retrieves the data. Must be called before DailyMissionData.GroupData
func (a *DailyMissionDataAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/DailyMissionData.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *DailyMissionDataAccessor) Raw() ([]DailyMissionData, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []DailyMissionData{}, err
		}
		a.GroupData()
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with DailyMissionDataAccessor.LoadData to preload everything
func (a *DailyMissionDataAccessor) GroupData() {
	for _, d := range a._data {
		a._dataID[d.ID] = d
	}
}

// ByID returns the DailyMissionData uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *DailyMissionDataAccessor) ByID(identifier float64) (DailyMissionData, error) {
	if a._dataID == nil {
		err := a.LoadData()
		if err != nil {
			return DailyMissionData{}, err
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}
