package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type EvolveBuildShopConfig struct {
	BuffTextFormat hash.Hash                        `json:"BuffTextFormat"`
	Category       hash.Hash                        `json:"Category"`
	ID             float64                          `json:"ID"`
	ItemBackground string                           `json:"ItemBackground"`
	ItemIcon       string                           `json:"ItemIcon"`
	LvMax          float64                          `json:"LvMax"`
	MazeBuffID     float64                          `json:"MazeBuffID"`
	Name           hash.Hash                        `json:"Name"`
	ParamList      []hash.IntValue                  `json:"ParamList"`
	PriceList      []EvolveBuildShopConfigPriceList `json:"PriceList"`
	ShopDesc       hash.Hash                        `json:"ShopDesc"`
	ShopType       string                           `json:"ShopType"`
	TotalBuff      hash.Hash                        `json:"TotalBuff"`
}
type EvolveBuildShopConfigPriceList struct {
	BMABPMLHLIN float64 `json:"BMABPMLHLIN"`
	KHCKFBHCFPL float64 `json:"KHCKFBHCFPL"`
}
type EvolveBuildShopConfigAccessor struct {
	_data         []EvolveBuildShopConfig
	_dataID       map[float64]EvolveBuildShopConfig
	_dataItemIcon map[string]EvolveBuildShopConfig
}

// LoadData retrieves the data. Must be called before EvolveBuildShopConfig.GroupData
func (a *EvolveBuildShopConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/EvolveBuildShopConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *EvolveBuildShopConfigAccessor) Raw() ([]EvolveBuildShopConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []EvolveBuildShopConfig{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with EvolveBuildShopConfigAccessor.LoadData to preload everything
func (a *EvolveBuildShopConfigAccessor) GroupData() {
	for _, d := range a._data {
		a._dataID[d.ID] = d
		a._dataItemIcon[d.ItemIcon] = d
	}
}

// ByID returns the EvolveBuildShopConfig uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *EvolveBuildShopConfigAccessor) ByID(identifier float64) (EvolveBuildShopConfig, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return EvolveBuildShopConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}

// ByItemIcon returns the EvolveBuildShopConfig uniquely identified by ItemIcon
//
// Error is only non-nil if the source errors out
func (a *EvolveBuildShopConfigAccessor) ByItemIcon(identifier string) (EvolveBuildShopConfig, error) {
	if a._dataItemIcon == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return EvolveBuildShopConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataItemIcon[identifier], nil
}
