package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"net/http"
	"io"
	"encoding/json"
)

type ExpType struct {
	Exp    float64 `json:"Exp"`
	Level  float64 `json:"Level"`
	TypeID float64 `json:"TypeID"`
}
type ExpTypeAccessor struct {
	_data []ExpType
}

// LoadData retrieves the data. Must be called before ExpType.GroupData
func (a *ExpTypeAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ExpType.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ExpTypeAccessor) Raw() ([]ExpType, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ExpType{}, err
		}
		a.GroupData()
	}
	return a._data, nil
}
