package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"net/http"
	"io"
	"encoding/json"
)

type FarmStageUnlockConfig struct {
	FarmGachaIDList       []interface{} `json:"FarmGachaIDList"`
	FarmType              string        `json:"FarmType"`
	ID                    float64       `json:"ID"`
	UIEnterBattleArea     float64       `json:"UIEnterBattleArea"`
	UIEntranceBgPath      string        `json:"UIEntranceBgPath"`
	UIEnviromentConfig    string        `json:"UIEnviromentConfig"`
	UnlockWorldLevelEnd   float64       `json:"UnlockWorldLevelEnd"`
	UnlockWorldLevelStart float64       `json:"UnlockWorldLevelStart"`
}
type FarmStageUnlockConfigAccessor struct {
	_data                 []FarmStageUnlockConfig
	_dataID               map[float64]FarmStageUnlockConfig
	_dataUIEntranceBgPath map[string]FarmStageUnlockConfig
}

// LoadData retrieves the data. Must be called before FarmStageUnlockConfig.GroupData
func (a *FarmStageUnlockConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/FarmStageUnlockConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *FarmStageUnlockConfigAccessor) Raw() ([]FarmStageUnlockConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []FarmStageUnlockConfig{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with FarmStageUnlockConfigAccessor.LoadData to preload everything
func (a *FarmStageUnlockConfigAccessor) GroupData() {
	a._dataID = map[float64]FarmStageUnlockConfig{}
	a._dataUIEntranceBgPath = map[string]FarmStageUnlockConfig{}
	for _, d := range a._data {
		a._dataID[d.ID] = d
		a._dataUIEntranceBgPath[d.UIEntranceBgPath] = d
	}
}

// ByID returns the FarmStageUnlockConfig uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *FarmStageUnlockConfigAccessor) ByID(identifier float64) (FarmStageUnlockConfig, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return FarmStageUnlockConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}

// ByUIEntranceBgPath returns the FarmStageUnlockConfig uniquely identified by UIEntranceBgPath
//
// Error is only non-nil if the source errors out
func (a *FarmStageUnlockConfigAccessor) ByUIEntranceBgPath(identifier string) (FarmStageUnlockConfig, error) {
	if a._dataUIEntranceBgPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return FarmStageUnlockConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataUIEntranceBgPath[identifier], nil
}
