package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type FinishWayEventMission struct {
	FinishType    string        `json:"FinishType"`
	ID            json.Number   `json:"ID"`
	ParamInt1     json.Number   `json:"ParamInt1"`
	ParamInt2     json.Number   `json:"ParamInt2"`
	ParamInt3     json.Number   `json:"ParamInt3"`
	ParamIntList  []interface{} `json:"ParamIntList"`
	ParamItemList []interface{} `json:"ParamItemList"`
	ParamStr1     string        `json:"ParamStr1"`
	ParamType     string        `json:"ParamType"`
	Progress      json.Number   `json:"Progress"`
}
type FinishWayEventMissionAccessor struct {
	_data []FinishWayEventMission
}

// LoadData retrieves the data. Must be called before FinishWayEventMission.GroupData
func (a *FinishWayEventMissionAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/FinishWayEventMission.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *FinishWayEventMissionAccessor) Raw() ([]FinishWayEventMission, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []FinishWayEventMission{}, err
		}
	}
	return a._data, nil
}
