package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type FuncEntrance struct {
	FirstWorldText     string                 `json:"FirstWorldText"`
	FuncHudIconPath    string                 `json:"FuncHudIconPath"`
	FuncIconPath       string                 `json:"FuncIconPath"`
	FuncName           map[string]json.Number `json:"FuncName"`
	GotoID             json.Number            `json:"GotoID"`
	ID                 json.Number            `json:"ID"`
	IsLargeBtn         bool                   `json:"IsLargeBtn"`
	NotInScheduleToast map[string]json.Number `json:"NotInScheduleToast"`
	ParentSystem       json.Number            `json:"ParentSystem"`
	RedDot             string                 `json:"RedDot"`
	RedDotHud          string                 `json:"RedDotHud"`
	UnLockIconPath     string                 `json:"UnLockIconPath"`
	UnlockDesc         map[string]json.Number `json:"UnlockDesc"`
	UnlockID           json.Number            `json:"UnlockID"`
	UnlockMainMission  json.Number            `json:"UnlockMainMission"`
	UnlockPrompt       string                 `json:"UnlockPrompt"`
}
type FuncEntranceAccessor struct {
	_data   []FuncEntrance
	_dataID map[json.Number]FuncEntrance
}

// LoadData retrieves the data. Must be called before FuncEntrance.GroupData
func (a *FuncEntranceAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/FuncEntrance.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *FuncEntranceAccessor) Raw() ([]FuncEntrance, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []FuncEntrance{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with FuncEntranceAccessor.LoadData to preload everything
func (a *FuncEntranceAccessor) GroupData() {
	a._dataID = map[json.Number]FuncEntrance{}
	for _, d := range a._data {
		a._dataID[d.ID] = d
	}
}

// ByID returns the FuncEntrance uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *FuncEntranceAccessor) ByID(identifier json.Number) (FuncEntrance, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return FuncEntrance{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}
