package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type ItemDisplaySortNew struct {
	ID     json.Number `json:"ID"`
	Param  json.Number `json:"Param"`
	Rank   json.Number `json:"Rank"`
	SortID json.Number `json:"SortID"`
	Type   string      `json:"Type"`
}
type ItemDisplaySortNewAccessor struct {
	_data []ItemDisplaySortNew
}

// LoadData retrieves the data. Must be called before ItemDisplaySortNew.GroupData
func (a *ItemDisplaySortNewAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ItemDisplaySortNew.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ItemDisplaySortNewAccessor) Raw() ([]ItemDisplaySortNew, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ItemDisplaySortNew{}, err
		}
	}
	return a._data, nil
}
