package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type ItemConfigAvatarPlayerIcLD struct {
	CustomDataList       []interface{} `json:"CustomDataList"`
	ID                   float64       `json:"ID"`
	InventoryDisplayTag  float64       `json:"InventoryDisplayTag"`
	ItemAvatarIconPath   string        `json:"ItemAvatarIconPath"`
	ItemCurrencyIconPath string        `json:"ItemCurrencyIconPath"`
	ItemFigureIconPath   string        `json:"ItemFigureIconPath"`
	ItemIconPath         string        `json:"ItemIconPath"`
	ItemMainType         string        `json:"ItemMainType"`
	ItemName             hash.Hash     `json:"ItemName"`
	ItemSubType          string        `json:"ItemSubType"`
	PileLimit            float64       `json:"PileLimit"`
	Rarity               string        `json:"Rarity"`
	ReturnItemIDList     []interface{} `json:"ReturnItemIDList"`
	UseMethod            string        `json:"UseMethod"`
	IsVisible            bool          `json:"isVisible"`
}
type ItemConfigAvatarPlayerIcLDAccessor struct {
	_data             []ItemConfigAvatarPlayerIcLD
	_dataID           map[float64]ItemConfigAvatarPlayerIcLD
	_dataItemIconPath map[string]ItemConfigAvatarPlayerIcLD
}

// LoadData retrieves the data. Must be called before ItemConfigAvatarPlayerIcLD.GroupData
func (a *ItemConfigAvatarPlayerIcLDAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ItemConfigAvatarPlayerIcLD.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ItemConfigAvatarPlayerIcLDAccessor) Raw() ([]ItemConfigAvatarPlayerIcLD, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ItemConfigAvatarPlayerIcLD{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ItemConfigAvatarPlayerIcLDAccessor.LoadData to preload everything
func (a *ItemConfigAvatarPlayerIcLDAccessor) GroupData() {
	a._dataID = map[float64]ItemConfigAvatarPlayerIcLD{}
	a._dataItemIconPath = map[string]ItemConfigAvatarPlayerIcLD{}
	for _, d := range a._data {
		a._dataID[d.ID] = d
		a._dataItemIconPath[d.ItemIconPath] = d
	}
}

// ByID returns the ItemConfigAvatarPlayerIcLD uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *ItemConfigAvatarPlayerIcLDAccessor) ByID(identifier float64) (ItemConfigAvatarPlayerIcLD, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ItemConfigAvatarPlayerIcLD{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}

// ByItemIconPath returns the ItemConfigAvatarPlayerIcLD uniquely identified by ItemIconPath
//
// Error is only non-nil if the source errors out
func (a *ItemConfigAvatarPlayerIcLDAccessor) ByItemIconPath(identifier string) (ItemConfigAvatarPlayerIcLD, error) {
	if a._dataItemIconPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ItemConfigAvatarPlayerIcLD{}, err
			}
		}
		a.GroupData()
	}
	return a._dataItemIconPath[identifier], nil
}
