package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type ItemConfigEquipment struct {
	CustomDataList       []interface{}            `json:"CustomDataList"`
	ID                   json.Number              `json:"ID"`
	InventoryDisplayTag  json.Number              `json:"InventoryDisplayTag"`
	ItemAvatarIconPath   string                   `json:"ItemAvatarIconPath"`
	ItemBGDesc           map[string]json.Number   `json:"ItemBGDesc"`
	ItemCurrencyIconPath string                   `json:"ItemCurrencyIconPath"`
	ItemDesc             map[string]json.Number   `json:"ItemDesc"`
	ItemFigureIconPath   string                   `json:"ItemFigureIconPath"`
	ItemIconPath         string                   `json:"ItemIconPath"`
	ItemMainType         string                   `json:"ItemMainType"`
	ItemName             map[string]json.Number   `json:"ItemName"`
	ItemSubType          string                   `json:"ItemSubType"`
	PileLimit            json.Number              `json:"PileLimit"`
	Rarity               string                   `json:"Rarity"`
	ReturnItemIDList     []map[string]json.Number `json:"ReturnItemIDList"`
	SellType             string                   `json:"SellType"`
	IsVisible            bool                     `json:"isVisible"`
}
type ItemConfigEquipmentAccessor struct {
	_data                   []ItemConfigEquipment
	_dataItemFigureIconPath map[string]ItemConfigEquipment
	_dataItemIconPath       map[string]ItemConfigEquipment
}

// LoadData retrieves the data. Must be called before ItemConfigEquipment.GroupData
func (a *ItemConfigEquipmentAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ItemConfigEquipment.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ItemConfigEquipmentAccessor) Raw() ([]ItemConfigEquipment, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ItemConfigEquipment{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ItemConfigEquipmentAccessor.LoadData to preload everything
func (a *ItemConfigEquipmentAccessor) GroupData() {
	a._dataItemFigureIconPath = map[string]ItemConfigEquipment{}
	a._dataItemIconPath = map[string]ItemConfigEquipment{}
	for _, d := range a._data {
		a._dataItemFigureIconPath[d.ItemFigureIconPath] = d
		a._dataItemIconPath[d.ItemIconPath] = d
	}
}

// ByItemFigureIconPath returns the ItemConfigEquipment uniquely identified by ItemFigureIconPath
//
// Error is only non-nil if the source errors out
func (a *ItemConfigEquipmentAccessor) ByItemFigureIconPath(identifier string) (ItemConfigEquipment, error) {
	if a._dataItemFigureIconPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ItemConfigEquipment{}, err
			}
		}
		a.GroupData()
	}
	return a._dataItemFigureIconPath[identifier], nil
}

// ByItemIconPath returns the ItemConfigEquipment uniquely identified by ItemIconPath
//
// Error is only non-nil if the source errors out
func (a *ItemConfigEquipmentAccessor) ByItemIconPath(identifier string) (ItemConfigEquipment, error) {
	if a._dataItemIconPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ItemConfigEquipment{}, err
			}
		}
		a.GroupData()
	}
	return a._dataItemIconPath[identifier], nil
}
