package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type ItemHintSpecial struct {
	IGIDDGDHAGI json.Number `json:"IGIDDGDHAGI"`
	KALHNEMJDEP bool        `json:"KALHNEMJDEP"`
}
type ItemHintSpecialAccessor struct {
	_data            []ItemHintSpecial
	_dataIGIDDGDHAGI map[json.Number]ItemHintSpecial
}

// LoadData retrieves the data. Must be called before ItemHintSpecial.GroupData
func (a *ItemHintSpecialAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ItemHintSpecial.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ItemHintSpecialAccessor) Raw() ([]ItemHintSpecial, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ItemHintSpecial{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ItemHintSpecialAccessor.LoadData to preload everything
func (a *ItemHintSpecialAccessor) GroupData() {
	a._dataIGIDDGDHAGI = map[json.Number]ItemHintSpecial{}
	for _, d := range a._data {
		a._dataIGIDDGDHAGI[d.IGIDDGDHAGI] = d
	}
}

// ByIGIDDGDHAGI returns the ItemHintSpecial uniquely identified by IGIDDGDHAGI
//
// Error is only non-nil if the source errors out
func (a *ItemHintSpecialAccessor) ByIGIDDGDHAGI(identifier json.Number) (ItemHintSpecial, error) {
	if a._dataIGIDDGDHAGI == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ItemHintSpecial{}, err
			}
		}
		a.GroupData()
	}
	return a._dataIGIDDGDHAGI[identifier], nil
}
