package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type LocalbookConfig struct {
	BookContent        map[string]json.Number `json:"BookContent"`
	BookDisplayType    json.Number            `json:"BookDisplayType"`
	BookID             json.Number            `json:"BookID"`
	BookInsideName     map[string]json.Number `json:"BookInsideName"`
	BookSeriesID       json.Number            `json:"BookSeriesID"`
	BookSeriesInsideID json.Number            `json:"BookSeriesInsideID"`
	LocalBookImagePath []string               `json:"LocalBookImagePath"`
}
type LocalbookConfigAccessor struct {
	_data []LocalbookConfig
}

// LoadData retrieves the data. Must be called before LocalbookConfig.GroupData
func (a *LocalbookConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/LocalbookConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *LocalbookConfigAccessor) Raw() ([]LocalbookConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []LocalbookConfig{}, err
		}
	}
	return a._data, nil
}
