package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type MainMissionPack struct {
	MainMissionIdList []json.Number `json:"MainMissionIdList"`
	MissionPack       json.Number   `json:"MissionPack"`
}
type MainMissionPackAccessor struct {
	_data []MainMissionPack
}

// LoadData retrieves the data. Must be called before MainMissionPack.GroupData
func (a *MainMissionPackAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/MainMissionPack.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *MainMissionPackAccessor) Raw() ([]MainMissionPack, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []MainMissionPack{}, err
		}
	}
	return a._data, nil
}
