package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type MatchThreeOpponent struct {
	AIConfig     string                 `json:"AIConfig"`
	IconPath     string                 `json:"IconPath"`
	ImagePath    string                 `json:"ImagePath"`
	Level        json.Number            `json:"Level"`
	MapImagePath string                 `json:"MapImagePath"`
	Nickname     map[string]json.Number `json:"Nickname"`
	OpponentID   json.Number            `json:"OpponentID"`
}
type MatchThreeOpponentAccessor struct {
	_data         []MatchThreeOpponent
	_dataAIConfig map[string]MatchThreeOpponent
}

// LoadData retrieves the data. Must be called before MatchThreeOpponent.GroupData
func (a *MatchThreeOpponentAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/MatchThreeOpponent.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *MatchThreeOpponentAccessor) Raw() ([]MatchThreeOpponent, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []MatchThreeOpponent{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with MatchThreeOpponentAccessor.LoadData to preload everything
func (a *MatchThreeOpponentAccessor) GroupData() {
	a._dataAIConfig = map[string]MatchThreeOpponent{}
	for _, d := range a._data {
		a._dataAIConfig[d.AIConfig] = d
	}
}

// ByAIConfig returns the MatchThreeOpponent uniquely identified by AIConfig
//
// Error is only non-nil if the source errors out
func (a *MatchThreeOpponentAccessor) ByAIConfig(identifier string) (MatchThreeOpponent, error) {
	if a._dataAIConfig == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return MatchThreeOpponent{}, err
			}
		}
		a.GroupData()
	}
	return a._dataAIConfig[identifier], nil
}
