package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type MazePuzzleDollyZoomTeleport struct {
	FloorID            json.Number `json:"FloorID"`
	GroupID            json.Number `json:"GroupID"`
	ID                 json.Number `json:"ID"`
	InstanceIDA        json.Number `json:"InstanceIDA"`
	InstanceIDB        json.Number `json:"InstanceIDB"`
	OverrideInitFOV    json.Number `json:"OverrideInitFOV"`
	OverridePosA       json.Number `json:"OverridePosA"`
	OverridePosB       json.Number `json:"OverridePosB"`
	OverrideTargetPosA json.Number `json:"OverrideTargetPosA"`
	OverrideTargetPosB json.Number `json:"OverrideTargetPosB"`
	PuzzlePrefab       string      `json:"PuzzlePrefab"`
}
type MazePuzzleDollyZoomTeleportAccessor struct {
	_data   []MazePuzzleDollyZoomTeleport
	_dataID map[json.Number]MazePuzzleDollyZoomTeleport
}

// LoadData retrieves the data. Must be called before MazePuzzleDollyZoomTeleport.GroupData
func (a *MazePuzzleDollyZoomTeleportAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/MazePuzzleDollyZoomTeleport.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *MazePuzzleDollyZoomTeleportAccessor) Raw() ([]MazePuzzleDollyZoomTeleport, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []MazePuzzleDollyZoomTeleport{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with MazePuzzleDollyZoomTeleportAccessor.LoadData to preload everything
func (a *MazePuzzleDollyZoomTeleportAccessor) GroupData() {
	a._dataID = map[json.Number]MazePuzzleDollyZoomTeleport{}
	for _, d := range a._data {
		a._dataID[d.ID] = d
	}
}

// ByID returns the MazePuzzleDollyZoomTeleport uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *MazePuzzleDollyZoomTeleportAccessor) ByID(identifier json.Number) (MazePuzzleDollyZoomTeleport, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return MazePuzzleDollyZoomTeleport{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}
