package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type MessageGroupConfig struct {
	ActivityModuleID     json.Number   `json:"ActivityModuleID"`
	ID                   json.Number   `json:"ID"`
	MessageContactsID    json.Number   `json:"MessageContactsID"`
	MessageSectionIDList []json.Number `json:"MessageSectionIDList"`
}
type MessageGroupConfigAccessor struct {
	_data []MessageGroupConfig
}

// LoadData retrieves the data. Must be called before MessageGroupConfig.GroupData
func (a *MessageGroupConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/MessageGroupConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *MessageGroupConfigAccessor) Raw() ([]MessageGroupConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []MessageGroupConfig{}, err
		}
	}
	return a._data, nil
}
