package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type MissionSubType struct {
	Type         string      `json:"Type"`
	TypePriority json.Number `json:"TypePriority"`
}
type MissionSubTypeAccessor struct {
	_data []MissionSubType
}

// LoadData retrieves the data. Must be called before MissionSubType.GroupData
func (a *MissionSubTypeAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/MissionSubType.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *MissionSubTypeAccessor) Raw() ([]MissionSubType, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []MissionSubType{}, err
		}
	}
	return a._data, nil
}
