package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type MonsterSkillConfig struct {
	AICD              float64         `json:"AI_CD"`
	AIICD             float64         `json:"AI_ICD"`
	AttackType        string          `json:"AttackType"`
	DamageType        string          `json:"DamageType"`
	DelayRatio        hash.IntValue   `json:"DelayRatio"`
	ExtraEffectIDList []float64       `json:"ExtraEffectIDList"`
	IconPath          string          `json:"IconPath"`
	IsThreat          bool            `json:"IsThreat"`
	ModifierList      []string        `json:"ModifierList"`
	ParamList         []hash.IntValue `json:"ParamList"`
	PhaseList         []float64       `json:"PhaseList"`
	SPHitBase         hash.IntValue   `json:"SPHitBase"`
	SkillDesc         hash.Hash       `json:"SkillDesc"`
	SkillID           float64         `json:"SkillID"`
	SkillName         hash.Hash       `json:"SkillName"`
	SkillTag          hash.Hash       `json:"SkillTag"`
	SkillTriggerKey   string          `json:"SkillTriggerKey"`
	SkillTypeDesc     hash.Hash       `json:"SkillTypeDesc"`
}
type MonsterSkillConfigAccessor struct {
	_data        []MonsterSkillConfig
	_dataSkillID map[float64]MonsterSkillConfig
}

// LoadData retrieves the data. Must be called before MonsterSkillConfig.GroupData
func (a *MonsterSkillConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/MonsterSkillConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *MonsterSkillConfigAccessor) Raw() ([]MonsterSkillConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []MonsterSkillConfig{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with MonsterSkillConfigAccessor.LoadData to preload everything
func (a *MonsterSkillConfigAccessor) GroupData() {
	for _, d := range a._data {
		a._dataSkillID[d.SkillID] = d
	}
}

// BySkillID returns the MonsterSkillConfig uniquely identified by SkillID
//
// Error is only non-nil if the source errors out
func (a *MonsterSkillConfigAccessor) BySkillID(identifier float64) (MonsterSkillConfig, error) {
	if a._dataSkillID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return MonsterSkillConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataSkillID[identifier], nil
}
