package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type MultiplePathAvatarConfig struct {
	AvatarID         json.Number                                `json:"AvatarID"`
	BaseAvatarID     json.Number                                `json:"BaseAvatarID"`
	ChangeConfigPath string                                     `json:"ChangeConfigPath"`
	Desc             map[string]json.Number                     `json:"Desc"`
	Gender           string                                     `json:"Gender"`
	IsEarlyUnlock    bool                                       `json:"IsEarlyUnlock"`
	UnlockConditions []MultiplePathAvatarConfigUnlockConditions `json:"UnlockConditions"`
	UnlockToast      map[string]json.Number                     `json:"UnlockToast"`
}
type MultiplePathAvatarConfigUnlockConditions struct {
	Param string `json:"Param"`
	Type  string `json:"Type"`
}
type MultiplePathAvatarConfigAccessor struct {
	_data                 []MultiplePathAvatarConfig
	_dataChangeConfigPath map[string]MultiplePathAvatarConfig
}

// LoadData retrieves the data. Must be called before MultiplePathAvatarConfig.GroupData
func (a *MultiplePathAvatarConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/MultiplePathAvatarConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *MultiplePathAvatarConfigAccessor) Raw() ([]MultiplePathAvatarConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []MultiplePathAvatarConfig{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with MultiplePathAvatarConfigAccessor.LoadData to preload everything
func (a *MultiplePathAvatarConfigAccessor) GroupData() {
	a._dataChangeConfigPath = map[string]MultiplePathAvatarConfig{}
	for _, d := range a._data {
		a._dataChangeConfigPath[d.ChangeConfigPath] = d
	}
}

// ByChangeConfigPath returns the MultiplePathAvatarConfig uniquely identified by ChangeConfigPath
//
// Error is only non-nil if the source errors out
func (a *MultiplePathAvatarConfigAccessor) ByChangeConfigPath(identifier string) (MultiplePathAvatarConfig, error) {
	if a._dataChangeConfigPath == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return MultiplePathAvatarConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataChangeConfigPath[identifier], nil
}
