package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type NPCData struct {
	ConfigEntityPath string    `json:"ConfigEntityPath"`
	DefaultNPCName   hash.Hash `json:"DefaultNPCName"`
	DefaultNPCTitle  hash.Hash `json:"DefaultNPCTitle"`
	ID               float64   `json:"ID"`
	JsonPath         string    `json:"JsonPath"`
	SeriesID         float64   `json:"SeriesID"`
	SubType          string    `json:"SubType"`
}
type NPCDataAccessor struct {
	_data   []NPCData
	_dataID map[float64]NPCData
}

// LoadData retrieves the data. Must be called before NPCData.GroupData
func (a *NPCDataAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/NPCData.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *NPCDataAccessor) Raw() ([]NPCData, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []NPCData{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with NPCDataAccessor.LoadData to preload everything
func (a *NPCDataAccessor) GroupData() {
	for _, d := range a._data {
		a._dataID[d.ID] = d
	}
}

// ByID returns the NPCData uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *NPCDataAccessor) ByID(identifier float64) (NPCData, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return NPCData{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}
