package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type ParkourTriggerEventContent struct {
	ID              float64   `json:"ID"`
	SpritePath      string    `json:"SpritePath"`
	TextContent     hash.Hash `json:"TextContent"`
	TriggerShowType string    `json:"TriggerShowType"`
}
type ParkourTriggerEventContentAccessor struct {
	_data   []ParkourTriggerEventContent
	_dataID map[float64]ParkourTriggerEventContent
}

// LoadData retrieves the data. Must be called before ParkourTriggerEventContent.GroupData
func (a *ParkourTriggerEventContentAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ParkourTriggerEventContent.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ParkourTriggerEventContentAccessor) Raw() ([]ParkourTriggerEventContent, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ParkourTriggerEventContent{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ParkourTriggerEventContentAccessor.LoadData to preload everything
func (a *ParkourTriggerEventContentAccessor) GroupData() {
	a._dataID = map[float64]ParkourTriggerEventContent{}
	for _, d := range a._data {
		a._dataID[d.ID] = d
	}
}

// ByID returns the ParkourTriggerEventContent uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *ParkourTriggerEventContentAccessor) ByID(identifier float64) (ParkourTriggerEventContent, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ParkourTriggerEventContent{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}
