package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type RaidLimitCondition struct {
	ID           json.Number            `json:"ID"`
	LimitDesc    map[string]json.Number `json:"LimitDesc"`
	LimitType    string                 `json:"LimitType"`
	ParamInt1    json.Number            `json:"ParamInt1"`
	ParamIntList []interface{}          `json:"ParamIntList"`
	ParamType    string                 `json:"ParamType"`
}
type RaidLimitConditionAccessor struct {
	_data []RaidLimitCondition
}

// LoadData retrieves the data. Must be called before RaidLimitCondition.GroupData
func (a *RaidLimitConditionAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RaidLimitCondition.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RaidLimitConditionAccessor) Raw() ([]RaidLimitCondition, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RaidLimitCondition{}, err
		}
	}
	return a._data, nil
}
