package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type RecolorConfig struct {
	DefaultColor string      `json:"DefaultColor"`
	ID           json.Number `json:"ID"`
	WhiteBGColor string      `json:"WhiteBGColor"`
}
type RecolorConfigAccessor struct {
	_data []RecolorConfig
}

// LoadData retrieves the data. Must be called before RecolorConfig.GroupData
func (a *RecolorConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RecolorConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RecolorConfigAccessor) Raw() ([]RecolorConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RecolorConfig{}, err
		}
	}
	return a._data, nil
}
