package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type RogueMagicRoom struct {
	RogueRoomID   json.Number `json:"RogueRoomID"`
	RogueRoomType string      `json:"RogueRoomType"`
}
type RogueMagicRoomAccessor struct {
	_data            []RogueMagicRoom
	_dataRogueRoomID map[json.Number]RogueMagicRoom
}

// LoadData retrieves the data. Must be called before RogueMagicRoom.GroupData
func (a *RogueMagicRoomAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RogueMagicRoom.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RogueMagicRoomAccessor) Raw() ([]RogueMagicRoom, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RogueMagicRoom{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with RogueMagicRoomAccessor.LoadData to preload everything
func (a *RogueMagicRoomAccessor) GroupData() {
	a._dataRogueRoomID = map[json.Number]RogueMagicRoom{}
	for _, d := range a._data {
		a._dataRogueRoomID[d.RogueRoomID] = d
	}
}

// ByRogueRoomID returns the RogueMagicRoom uniquely identified by RogueRoomID
//
// Error is only non-nil if the source errors out
func (a *RogueMagicRoomAccessor) ByRogueRoomID(identifier json.Number) (RogueMagicRoom, error) {
	if a._dataRogueRoomID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return RogueMagicRoom{}, err
			}
		}
		a.GroupData()
	}
	return a._dataRogueRoomID[identifier], nil
}
