package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type RogueNousMiscDisplay struct {
	DisplayContent hash.Hash `json:"DisplayContent"`
	DisplayID      float64   `json:"DisplayID"`
}
type RogueNousMiscDisplayAccessor struct {
	_data          []RogueNousMiscDisplay
	_dataDisplayID map[float64]RogueNousMiscDisplay
}

// LoadData retrieves the data. Must be called before RogueNousMiscDisplay.GroupData
func (a *RogueNousMiscDisplayAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RogueNousMiscDisplay.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RogueNousMiscDisplayAccessor) Raw() ([]RogueNousMiscDisplay, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RogueNousMiscDisplay{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with RogueNousMiscDisplayAccessor.LoadData to preload everything
func (a *RogueNousMiscDisplayAccessor) GroupData() {
	a._dataDisplayID = map[float64]RogueNousMiscDisplay{}
	for _, d := range a._data {
		a._dataDisplayID[d.DisplayID] = d
	}
}

// ByDisplayID returns the RogueNousMiscDisplay uniquely identified by DisplayID
//
// Error is only non-nil if the source errors out
func (a *RogueNousMiscDisplayAccessor) ByDisplayID(identifier float64) (RogueNousMiscDisplay, error) {
	if a._dataDisplayID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return RogueNousMiscDisplay{}, err
			}
		}
		a.GroupData()
	}
	return a._dataDisplayID[identifier], nil
}
