package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type RogueTournFinishway struct {
	FinishType    string        `json:"FinishType"`
	ID            json.Number   `json:"ID"`
	IsBackTrack   bool          `json:"IsBackTrack"`
	ParamInt1     json.Number   `json:"ParamInt1"`
	ParamInt2     json.Number   `json:"ParamInt2"`
	ParamInt3     json.Number   `json:"ParamInt3"`
	ParamIntList  []json.Number `json:"ParamIntList"`
	ParamItemList []interface{} `json:"ParamItemList"`
	ParamStr1     string        `json:"ParamStr1"`
	ParamType     string        `json:"ParamType"`
	Progress      json.Number   `json:"Progress"`
}
type RogueTournFinishwayAccessor struct {
	_data   []RogueTournFinishway
	_dataID map[json.Number]RogueTournFinishway
}

// LoadData retrieves the data. Must be called before RogueTournFinishway.GroupData
func (a *RogueTournFinishwayAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RogueTournFinishway.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RogueTournFinishwayAccessor) Raw() ([]RogueTournFinishway, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RogueTournFinishway{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with RogueTournFinishwayAccessor.LoadData to preload everything
func (a *RogueTournFinishwayAccessor) GroupData() {
	a._dataID = map[json.Number]RogueTournFinishway{}
	for _, d := range a._data {
		a._dataID[d.ID] = d
	}
}

// ByID returns the RogueTournFinishway uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *RogueTournFinishwayAccessor) ByID(identifier json.Number) (RogueTournFinishway, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return RogueTournFinishway{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}
