package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"net/http"
	"io"
	"encoding/json"
)

type RogueTournAdventureRoom struct {
	AdventureType string  `json:"AdventureType"`
	ParamGroupID  float64 `json:"ParamGroupID"`
	RoomID        float64 `json:"RoomID"`
}
type RogueTournAdventureRoomAccessor struct {
	_data       []RogueTournAdventureRoom
	_dataRoomID map[float64]RogueTournAdventureRoom
}

// LoadData retrieves the data. Must be called before RogueTournAdventureRoom.GroupData
func (a *RogueTournAdventureRoomAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RogueTournAdventureRoom.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RogueTournAdventureRoomAccessor) Raw() ([]RogueTournAdventureRoom, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RogueTournAdventureRoom{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with RogueTournAdventureRoomAccessor.LoadData to preload everything
func (a *RogueTournAdventureRoomAccessor) GroupData() {
	a._dataRoomID = map[float64]RogueTournAdventureRoom{}
	for _, d := range a._data {
		a._dataRoomID[d.RoomID] = d
	}
}

// ByRoomID returns the RogueTournAdventureRoom uniquely identified by RoomID
//
// Error is only non-nil if the source errors out
func (a *RogueTournAdventureRoomAccessor) ByRoomID(identifier float64) (RogueTournAdventureRoom, error) {
	if a._dataRoomID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return RogueTournAdventureRoom{}, err
			}
		}
		a.GroupData()
	}
	return a._dataRoomID[identifier], nil
}
