package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type RogueDestroyProp struct {
	GameTime     json.Number   `json:"GameTime"`
	ParamGroupID json.Number   `json:"ParamGroupID"`
	PrepareTime  json.Number   `json:"PrepareTime"`
	ScoreRange   []json.Number `json:"ScoreRange"`
}
type RogueDestroyPropAccessor struct {
	_data             []RogueDestroyProp
	_dataParamGroupID map[json.Number]RogueDestroyProp
}

// LoadData retrieves the data. Must be called before RogueDestroyProp.GroupData
func (a *RogueDestroyPropAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RogueDestroyProp.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RogueDestroyPropAccessor) Raw() ([]RogueDestroyProp, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RogueDestroyProp{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with RogueDestroyPropAccessor.LoadData to preload everything
func (a *RogueDestroyPropAccessor) GroupData() {
	a._dataParamGroupID = map[json.Number]RogueDestroyProp{}
	for _, d := range a._data {
		a._dataParamGroupID[d.ParamGroupID] = d
	}
}

// ByParamGroupID returns the RogueDestroyProp uniquely identified by ParamGroupID
//
// Error is only non-nil if the source errors out
func (a *RogueDestroyPropAccessor) ByParamGroupID(identifier json.Number) (RogueDestroyProp, error) {
	if a._dataParamGroupID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return RogueDestroyProp{}, err
			}
		}
		a.GroupData()
	}
	return a._dataParamGroupID[identifier], nil
}
