package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type RogueTournRoom struct {
	RogueRoomID   json.Number `json:"RogueRoomID"`
	RogueRoomType string      `json:"RogueRoomType"`
	TournMode     string      `json:"TournMode"`
	VariantType   string      `json:"VariantType"`
}
type RogueTournRoomAccessor struct {
	_data []RogueTournRoom
}

// LoadData retrieves the data. Must be called before RogueTournRoom.GroupData
func (a *RogueTournRoomAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RogueTournRoom.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RogueTournRoomAccessor) Raw() ([]RogueTournRoom, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RogueTournRoom{}, err
		}
	}
	return a._data, nil
}
