package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type RogueDLCLayer struct {
	LayerID     float64   `json:"LayerID"`
	LayerIcon   string    `json:"LayerIcon"`
	LayerNameID hash.Hash `json:"LayerNameID"`
	LayerNumID  hash.Hash `json:"LayerNumID"`
}
type RogueDLCLayerAccessor struct {
	_data        []RogueDLCLayer
	_dataLayerID map[float64]RogueDLCLayer
}

// LoadData retrieves the data. Must be called before RogueDLCLayer.GroupData
func (a *RogueDLCLayerAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RogueDLCLayer.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RogueDLCLayerAccessor) Raw() ([]RogueDLCLayer, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RogueDLCLayer{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with RogueDLCLayerAccessor.LoadData to preload everything
func (a *RogueDLCLayerAccessor) GroupData() {
	a._dataLayerID = map[float64]RogueDLCLayer{}
	for _, d := range a._data {
		a._dataLayerID[d.LayerID] = d
	}
}

// ByLayerID returns the RogueDLCLayer uniquely identified by LayerID
//
// Error is only non-nil if the source errors out
func (a *RogueDLCLayerAccessor) ByLayerID(identifier float64) (RogueDLCLayer, error) {
	if a._dataLayerID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return RogueDLCLayer{}, err
			}
		}
		a.GroupData()
	}
	return a._dataLayerID[identifier], nil
}
