package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type RogueMagicTalent struct {
	Cost          []map[string]json.Number     `json:"Cost"`
	DescParams    []RogueMagicTalentDescParams `json:"DescParams"`
	EffectDesc    map[string]json.Number       `json:"EffectDesc"`
	Level         json.Number                  `json:"Level"`
	NameDisplayID json.Number                  `json:"NameDisplayID"`
	TalentID      json.Number                  `json:"TalentID"`
	TalentIcon    string                       `json:"TalentIcon"`
}
type RogueMagicTalentDescParams struct {
	HMCDHMFHABF string `json:"HMCDHMFHABF"`
	PICHIHHCOCB string `json:"PICHIHHCOCB"`
}
type RogueMagicTalentAccessor struct {
	_data         []RogueMagicTalent
	_dataLevel    map[json.Number]RogueMagicTalent
	_dataTalentID map[json.Number]RogueMagicTalent
}

// LoadData retrieves the data. Must be called before RogueMagicTalent.GroupData
func (a *RogueMagicTalentAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/RogueMagicTalent.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *RogueMagicTalentAccessor) Raw() ([]RogueMagicTalent, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []RogueMagicTalent{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with RogueMagicTalentAccessor.LoadData to preload everything
func (a *RogueMagicTalentAccessor) GroupData() {
	a._dataLevel = map[json.Number]RogueMagicTalent{}
	a._dataTalentID = map[json.Number]RogueMagicTalent{}
	for _, d := range a._data {
		a._dataLevel[d.Level] = d
		a._dataTalentID[d.TalentID] = d
	}
}

// ByLevel returns the RogueMagicTalent uniquely identified by Level
//
// Error is only non-nil if the source errors out
func (a *RogueMagicTalentAccessor) ByLevel(identifier json.Number) (RogueMagicTalent, error) {
	if a._dataLevel == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return RogueMagicTalent{}, err
			}
		}
		a.GroupData()
	}
	return a._dataLevel[identifier], nil
}

// ByTalentID returns the RogueMagicTalent uniquely identified by TalentID
//
// Error is only non-nil if the source errors out
func (a *RogueMagicTalentAccessor) ByTalentID(identifier json.Number) (RogueMagicTalent, error) {
	if a._dataTalentID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return RogueMagicTalent{}, err
			}
		}
		a.GroupData()
	}
	return a._dataTalentID[identifier], nil
}
