package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type ScheduleDataShop struct {
	BeginTime string      `json:"BeginTime"`
	EndTime   string      `json:"EndTime"`
	ID        json.Number `json:"ID"`
}
type ScheduleDataShopAccessor struct {
	_data []ScheduleDataShop
}

// LoadData retrieves the data. Must be called before ScheduleDataShop.GroupData
func (a *ScheduleDataShopAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ScheduleDataShop.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ScheduleDataShopAccessor) Raw() ([]ScheduleDataShop, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ScheduleDataShop{}, err
		}
	}
	return a._data, nil
}
