package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"net/http"
	"io"
	"encoding/json"
)

type ScheduleDataChallengeBoss struct {
	BeginTime string  `json:"BeginTime"`
	EndTime   string  `json:"EndTime"`
	ID        float64 `json:"ID"`
}
type ScheduleDataChallengeBossAccessor struct {
	_data          []ScheduleDataChallengeBoss
	_dataBeginTime map[string]ScheduleDataChallengeBoss
	_dataEndTime   map[string]ScheduleDataChallengeBoss
	_dataID        map[float64]ScheduleDataChallengeBoss
}

// LoadData retrieves the data. Must be called before ScheduleDataChallengeBoss.GroupData
func (a *ScheduleDataChallengeBossAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ScheduleDataChallengeBoss.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ScheduleDataChallengeBossAccessor) Raw() ([]ScheduleDataChallengeBoss, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ScheduleDataChallengeBoss{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with ScheduleDataChallengeBossAccessor.LoadData to preload everything
func (a *ScheduleDataChallengeBossAccessor) GroupData() {
	for _, d := range a._data {
		a._dataBeginTime[d.BeginTime] = d
		a._dataEndTime[d.EndTime] = d
		a._dataID[d.ID] = d
	}
}

// ByBeginTime returns the ScheduleDataChallengeBoss uniquely identified by BeginTime
//
// Error is only non-nil if the source errors out
func (a *ScheduleDataChallengeBossAccessor) ByBeginTime(identifier string) (ScheduleDataChallengeBoss, error) {
	if a._dataBeginTime == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ScheduleDataChallengeBoss{}, err
			}
		}
		a.GroupData()
	}
	return a._dataBeginTime[identifier], nil
}

// ByEndTime returns the ScheduleDataChallengeBoss uniquely identified by EndTime
//
// Error is only non-nil if the source errors out
func (a *ScheduleDataChallengeBossAccessor) ByEndTime(identifier string) (ScheduleDataChallengeBoss, error) {
	if a._dataEndTime == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ScheduleDataChallengeBoss{}, err
			}
		}
		a.GroupData()
	}
	return a._dataEndTime[identifier], nil
}

// ByID returns the ScheduleDataChallengeBoss uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *ScheduleDataChallengeBossAccessor) ByID(identifier float64) (ScheduleDataChallengeBoss, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return ScheduleDataChallengeBoss{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}
