package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type ScoringGroup struct {
	DisplayType    string                 `json:"DisplayType"`
	ScoreName      map[string]json.Number `json:"ScoreName"`
	ScoringGroupID json.Number            `json:"ScoringGroupID"`
	ScoringIDList  []json.Number          `json:"ScoringIDList"`
}
type ScoringGroupAccessor struct {
	_data []ScoringGroup
}

// LoadData retrieves the data. Must be called before ScoringGroup.GroupData
func (a *ScoringGroupAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/ScoringGroup.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *ScoringGroupAccessor) Raw() ([]ScoringGroup, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []ScoringGroup{}, err
		}
	}
	return a._data, nil
}
