package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type SpaceZooSpecialEvent struct {
	EventState       string                 `json:"EventState"`
	HintTip          map[string]json.Number `json:"HintTip"`
	SpecialCatID     json.Number            `json:"SpecialCatID"`
	SpecialCatIsMask string                 `json:"SpecialCatIsMask"`
}
type SpaceZooSpecialEventAccessor struct {
	_data []SpaceZooSpecialEvent
}

// LoadData retrieves the data. Must be called before SpaceZooSpecialEvent.GroupData
func (a *SpaceZooSpecialEventAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/SpaceZooSpecialEvent.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *SpaceZooSpecialEventAccessor) Raw() ([]SpaceZooSpecialEvent, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []SpaceZooSpecialEvent{}, err
		}
	}
	return a._data, nil
}
