package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type StatusConfig struct {
	CanDispel              bool                   `json:"CanDispel"`
	ModifierName           string                 `json:"ModifierName"`
	ReadParamList          []string               `json:"ReadParamList"`
	StatusDesc             map[string]json.Number `json:"StatusDesc"`
	StatusEffect           map[string]json.Number `json:"StatusEffect"`
	StatusID               json.Number            `json:"StatusID"`
	StatusIconPath         string                 `json:"StatusIconPath"`
	StatusIconPathHighSize string                 `json:"StatusIconPathHighSize"`
	StatusName             map[string]json.Number `json:"StatusName"`
	StatusType             string                 `json:"StatusType"`
	TagList                []string               `json:"TagList"`
}
type StatusConfigAccessor struct {
	_data             []StatusConfig
	_dataModifierName map[string]StatusConfig
	_dataStatusID     map[json.Number]StatusConfig
}

// LoadData retrieves the data. Must be called before StatusConfig.GroupData
func (a *StatusConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/StatusConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *StatusConfigAccessor) Raw() ([]StatusConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []StatusConfig{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with StatusConfigAccessor.LoadData to preload everything
func (a *StatusConfigAccessor) GroupData() {
	a._dataModifierName = map[string]StatusConfig{}
	a._dataStatusID = map[json.Number]StatusConfig{}
	for _, d := range a._data {
		a._dataModifierName[d.ModifierName] = d
		a._dataStatusID[d.StatusID] = d
	}
}

// ByModifierName returns the StatusConfig uniquely identified by ModifierName
//
// Error is only non-nil if the source errors out
func (a *StatusConfigAccessor) ByModifierName(identifier string) (StatusConfig, error) {
	if a._dataModifierName == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return StatusConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataModifierName[identifier], nil
}

// ByStatusID returns the StatusConfig uniquely identified by StatusID
//
// Error is only non-nil if the source errors out
func (a *StatusConfigAccessor) ByStatusID(identifier json.Number) (StatusConfig, error) {
	if a._dataStatusID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return StatusConfig{}, err
			}
		}
		a.GroupData()
	}
	return a._dataStatusID[identifier], nil
}
