package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type StrongChallengeBossDetail struct {
	BossDetailID float64   `json:"BossDetailID"`
	Detail       hash.Hash `json:"Detail"`
}
type StrongChallengeBossDetailAccessor struct {
	_data             []StrongChallengeBossDetail
	_dataBossDetailID map[float64]StrongChallengeBossDetail
}

// LoadData retrieves the data. Must be called before StrongChallengeBossDetail.GroupData
func (a *StrongChallengeBossDetailAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/StrongChallengeBossDetail.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *StrongChallengeBossDetailAccessor) Raw() ([]StrongChallengeBossDetail, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []StrongChallengeBossDetail{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with StrongChallengeBossDetailAccessor.LoadData to preload everything
func (a *StrongChallengeBossDetailAccessor) GroupData() {
	a._dataBossDetailID = map[float64]StrongChallengeBossDetail{}
	for _, d := range a._data {
		a._dataBossDetailID[d.BossDetailID] = d
	}
}

// ByBossDetailID returns the StrongChallengeBossDetail uniquely identified by BossDetailID
//
// Error is only non-nil if the source errors out
func (a *StrongChallengeBossDetailAccessor) ByBossDetailID(identifier float64) (StrongChallengeBossDetail, error) {
	if a._dataBossDetailID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return StrongChallengeBossDetail{}, err
			}
		}
		a.GroupData()
	}
	return a._dataBossDetailID[identifier], nil
}
