package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type SwordTrainingPartnerGroup struct {
	PartnerAbilityDrop    []json.Number `json:"PartnerAbilityDrop"`
	PartnerAbilityGroupID json.Number   `json:"PartnerAbilityGroupID"`
	PartnerAbilityWeight  json.Number   `json:"PartnerAbilityWeight"`
}
type SwordTrainingPartnerGroupAccessor struct {
	_data []SwordTrainingPartnerGroup
}

// LoadData retrieves the data. Must be called before SwordTrainingPartnerGroup.GroupData
func (a *SwordTrainingPartnerGroupAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/SwordTrainingPartnerGroup.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *SwordTrainingPartnerGroupAccessor) Raw() ([]SwordTrainingPartnerGroup, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []SwordTrainingPartnerGroup{}, err
		}
	}
	return a._data, nil
}
