package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type TarotBookClue struct {
	ID    json.Number            `json:"ID"`
	Name  map[string]json.Number `json:"Name"`
	Style json.Number            `json:"Style"`
}
type TarotBookClueAccessor struct {
	_data []TarotBookClue
}

// LoadData retrieves the data. Must be called before TarotBookClue.GroupData
func (a *TarotBookClueAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/TarotBookClue.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *TarotBookClueAccessor) Raw() ([]TarotBookClue, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []TarotBookClue{}, err
		}
	}
	return a._data, nil
}
