package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type TarotBookCommonConstValue struct {
	ConstValueName string        `json:"ConstValueName"`
	Value          hash.IntValue `json:"Value"`
}
type TarotBookCommonConstValueAccessor struct {
	_data               []TarotBookCommonConstValue
	_dataConstValueName map[string]TarotBookCommonConstValue
}

// LoadData retrieves the data. Must be called before TarotBookCommonConstValue.GroupData
func (a *TarotBookCommonConstValueAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/TarotBookCommonConstValue.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *TarotBookCommonConstValueAccessor) Raw() ([]TarotBookCommonConstValue, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []TarotBookCommonConstValue{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with TarotBookCommonConstValueAccessor.LoadData to preload everything
func (a *TarotBookCommonConstValueAccessor) GroupData() {
	a._dataConstValueName = map[string]TarotBookCommonConstValue{}
	for _, d := range a._data {
		a._dataConstValueName[d.ConstValueName] = d
	}
}

// ByConstValueName returns the TarotBookCommonConstValue uniquely identified by ConstValueName
//
// Error is only non-nil if the source errors out
func (a *TarotBookCommonConstValueAccessor) ByConstValueName(identifier string) (TarotBookCommonConstValue, error) {
	if a._dataConstValueName == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return TarotBookCommonConstValue{}, err
			}
		}
		a.GroupData()
	}
	return a._dataConstValueName[identifier], nil
}
