package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"github.com/Fesaa/enka-network-api-go/hash"
	"net/http"
	"io"
	"encoding/json"
)

type TarotBookClue struct {
	ID    float64   `json:"ID"`
	Name  hash.Hash `json:"Name"`
	Style float64   `json:"Style"`
}
type TarotBookClueAccessor struct {
	_data   []TarotBookClue
	_dataID map[float64]TarotBookClue
}

// LoadData retrieves the data. Must be called before TarotBookClue.GroupData
func (a *TarotBookClueAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/TarotBookClue.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *TarotBookClueAccessor) Raw() ([]TarotBookClue, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []TarotBookClue{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with TarotBookClueAccessor.LoadData to preload everything
func (a *TarotBookClueAccessor) GroupData() {
	for _, d := range a._data {
		a._dataID[d.ID] = d
	}
}

// ByID returns the TarotBookClue uniquely identified by ID
//
// Error is only non-nil if the source errors out
func (a *TarotBookClueAccessor) ByID(identifier float64) (TarotBookClue, error) {
	if a._dataID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return TarotBookClue{}, err
			}
		}
		a.GroupData()
	}
	return a._dataID[identifier], nil
}
