package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type TeleportConfig struct {
	ConfigID      json.Number `json:"ConfigID"`
	FloorID       json.Number `json:"FloorID"`
	GroupID       json.Number `json:"GroupID"`
	ID            json.Number `json:"ID"`
	InitialEnable bool        `json:"InitialEnable"`
	PlaneID       json.Number `json:"PlaneID"`
}
type TeleportConfigAccessor struct {
	_data []TeleportConfig
}

// LoadData retrieves the data. Must be called before TeleportConfig.GroupData
func (a *TeleportConfigAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/TeleportConfig.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *TeleportConfigAccessor) Raw() ([]TeleportConfig, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []TeleportConfig{}, err
		}
	}
	return a._data, nil
}
