package // Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"io"
	"net/http"
)

type TitanAtlasChangeInfo struct {
	ChangeTitanIDList []json.Number `json:"ChangeTitanIDList"`
	TitanID           json.Number   `json:"TitanID"`
}
type TitanAtlasChangeInfoAccessor struct {
	_data []TitanAtlasChangeInfo
}

// LoadData retrieves the data. Must be called before TitanAtlasChangeInfo.GroupData
func (a *TitanAtlasChangeInfoAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/TitanAtlasChangeInfo.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *TitanAtlasChangeInfoAccessor) Raw() ([]TitanAtlasChangeInfo, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []TitanAtlasChangeInfo{}, err
		}
	}
	return a._data, nil
}
