package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type TitanAtlasChangeInfo struct {
	ChangeTitanIDList []json.Number `json:"ChangeTitanIDList"`
	TitanID           json.Number   `json:"TitanID"`
}
type TitanAtlasChangeInfoAccessor struct {
	_data        []TitanAtlasChangeInfo
	_dataTitanID map[json.Number]TitanAtlasChangeInfo
}

// LoadData retrieves the data. Must be called before TitanAtlasChangeInfo.GroupData
func (a *TitanAtlasChangeInfoAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/TitanAtlasChangeInfo.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *TitanAtlasChangeInfoAccessor) Raw() ([]TitanAtlasChangeInfo, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []TitanAtlasChangeInfo{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with TitanAtlasChangeInfoAccessor.LoadData to preload everything
func (a *TitanAtlasChangeInfoAccessor) GroupData() {
	a._dataTitanID = map[json.Number]TitanAtlasChangeInfo{}
	for _, d := range a._data {
		a._dataTitanID[d.TitanID] = d
	}
}

// ByTitanID returns the TitanAtlasChangeInfo uniquely identified by TitanID
//
// Error is only non-nil if the source errors out
func (a *TitanAtlasChangeInfoAccessor) ByTitanID(identifier json.Number) (TitanAtlasChangeInfo, error) {
	if a._dataTitanID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return TitanAtlasChangeInfo{}, err
			}
		}
		a.GroupData()
	}
	return a._dataTitanID[identifier], nil
}
