package// Generated by Yoitsu. DO NOT EDIT!
excels

import (
	"encoding/json"
	"net/http"
	"io"
)

type TrainPartyProgress struct {
	CoinRatio              json.Number            `json:"CoinRatio"`
	InitialStatExp         json.Number            `json:"InitialStatExp"`
	PassengerUnlockActPath string                 `json:"PassengerUnlockActPath"`
	ProgressID             json.Number            `json:"ProgressID"`
	ProgressTitle          map[string]json.Number `json:"ProgressTitle"`
	StatRatio              json.Number            `json:"StatRatio"`
	TeamIDList             []json.Number          `json:"TeamIDList"`
	UnlcokRequireArea      json.Number            `json:"UnlcokRequireArea"`
	UnlockPassengerList    []json.Number          `json:"UnlockPassengerList"`
}
type TrainPartyProgressAccessor struct {
	_data           []TrainPartyProgress
	_dataProgressID map[json.Number]TrainPartyProgress
}

// LoadData retrieves the data. Must be called before TrainPartyProgress.GroupData
func (a *TrainPartyProgressAccessor) LoadData() error {
	res, err := http.Get("https://gitlab.com/Dimbreath/turnbasedgamedata/-/raw/main/ExcelOutput/TrainPartyProgress.json")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &a._data)
}

// Raw returns the raw data.
func (a *TrainPartyProgressAccessor) Raw() ([]TrainPartyProgress, error) {
	if a._data == nil {
		err := a.LoadData()
		if err != nil {
			return []TrainPartyProgress{}, err
		}
	}
	return a._data, nil
}

// GroupData groups the data by their unique ids.
// Can be called manually in conjunction with TrainPartyProgressAccessor.LoadData to preload everything
func (a *TrainPartyProgressAccessor) GroupData() {
	a._dataProgressID = map[json.Number]TrainPartyProgress{}
	for _, d := range a._data {
		a._dataProgressID[d.ProgressID] = d
	}
}

// ByProgressID returns the TrainPartyProgress uniquely identified by ProgressID
//
// Error is only non-nil if the source errors out
func (a *TrainPartyProgressAccessor) ByProgressID(identifier json.Number) (TrainPartyProgress, error) {
	if a._dataProgressID == nil {
		if a._data == nil {
			err := a.LoadData()
			if err != nil {
				return TrainPartyProgress{}, err
			}
		}
		a.GroupData()
	}
	return a._dataProgressID[identifier], nil
}
